# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files and install dependencies
COPY browserbase/package*.json ./browserbase/
RUN cd browserbase && npm install --ignore-scripts

# Copy the rest of the browserbase source code
COPY browserbase/ ./browserbase/

# Build the project
RUN cd browserbase && npm run build

# Expose port if needed (optional)

# Start the MCP server
CMD ["node", "browserbase/dist/index.js"]
